# Generated by Django 5.2.5 on 2025-08-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuarioperfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='estabelecimentos/'),
        ),
        migrations.AddField(
            model_name='produto',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
